import { AIEvidenceEpistemicTier, AIPrivacyLevel } from '../value-objects/enums';

/** Evidence Dictionary class keys (docs/aether-os-v2/AETHER-OS-V2-AI-EVIDENCE-DICTIONARY.md) */
export const EVIDENCE_CLASS_KEYS = {
  Session: 'EV-Session',
  Reflection: 'EV-Reflection',
  Artifact: 'EV-Artifact',
  Analytics: 'EV-Analytics',
  Signal: 'EV-Signal',
  LifeScore: 'EV-LifeScore',
  Mastery: 'EV-Mastery',
  Season: 'EV-Season',
  Journey: 'EV-Journey',
  Project: 'EV-Project',
  System: 'EV-System',
  Knowledge: 'EV-Knowledge',
  Body: 'EV-Body',
  Brand: 'EV-Brand',
  Career: 'EV-Career',
  Spirit: 'EV-Spirit',
  Finance: 'EV-Finance',
  Relationships: 'EV-Relationships',
  Mind: 'EV-Mind',
  Legacy: 'EV-Legacy',
  DailyAction: 'EV-DailyAction',
  Proposal: 'EV-Proposal',
  Insight: 'EV-Insight',
  ChatTurn: 'EV-ChatTurn',
} as const;

export type EvidenceClassKey = (typeof EVIDENCE_CLASS_KEYS)[keyof typeof EVIDENCE_CLASS_KEYS];

export interface EvidenceClassDefinition {
  classKey: EvidenceClassKey;
  entityType: string;
  tier: AIEvidenceEpistemicTier;
  privacyLevel: AIPrivacyLevel;
  retrievalPriority: number;
  /** Progress claims must chain to these for high-confidence factual statements */
  progressClaimAllowed: boolean;
}

export const EVIDENCE_CLASS_REGISTRY: Record<EvidenceClassKey, EvidenceClassDefinition> = {
  [EVIDENCE_CLASS_KEYS.Session]: {
    classKey: EVIDENCE_CLASS_KEYS.Session,
    entityType: 'Session',
    tier: AIEvidenceEpistemicTier.Authoritative,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 1,
    progressClaimAllowed: true,
  },
  [EVIDENCE_CLASS_KEYS.Reflection]: {
    classKey: EVIDENCE_CLASS_KEYS.Reflection,
    entityType: 'Reflection',
    tier: AIEvidenceEpistemicTier.Authoritative,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 2,
    progressClaimAllowed: false,
  },
  [EVIDENCE_CLASS_KEYS.Artifact]: {
    classKey: EVIDENCE_CLASS_KEYS.Artifact,
    entityType: 'Artifact',
    tier: AIEvidenceEpistemicTier.Authoritative,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 2,
    progressClaimAllowed: true,
  },
  [EVIDENCE_CLASS_KEYS.Analytics]: {
    classKey: EVIDENCE_CLASS_KEYS.Analytics,
    entityType: 'AnalyticsSnapshot',
    tier: AIEvidenceEpistemicTier.Derived,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 3,
    progressClaimAllowed: true,
  },
  [EVIDENCE_CLASS_KEYS.Signal]: {
    classKey: EVIDENCE_CLASS_KEYS.Signal,
    entityType: 'InterconnectionSignal',
    tier: AIEvidenceEpistemicTier.Derived,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 2,
    progressClaimAllowed: false,
  },
  [EVIDENCE_CLASS_KEYS.LifeScore]: {
    classKey: EVIDENCE_CLASS_KEYS.LifeScore,
    entityType: 'LifeScore',
    tier: AIEvidenceEpistemicTier.Derived,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 4,
    progressClaimAllowed: false,
  },
  [EVIDENCE_CLASS_KEYS.Mastery]: {
    classKey: EVIDENCE_CLASS_KEYS.Mastery,
    entityType: 'MasteryState',
    tier: AIEvidenceEpistemicTier.Derived,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 4,
    progressClaimAllowed: false,
  },
  [EVIDENCE_CLASS_KEYS.Season]: {
    classKey: EVIDENCE_CLASS_KEYS.Season,
    entityType: 'Season',
    tier: AIEvidenceEpistemicTier.Authoritative,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 2,
    progressClaimAllowed: false,
  },
  [EVIDENCE_CLASS_KEYS.Journey]: {
    classKey: EVIDENCE_CLASS_KEYS.Journey,
    entityType: 'Journey',
    tier: AIEvidenceEpistemicTier.Authoritative,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 3,
    progressClaimAllowed: false,
  },
  [EVIDENCE_CLASS_KEYS.Project]: {
    classKey: EVIDENCE_CLASS_KEYS.Project,
    entityType: 'Project',
    tier: AIEvidenceEpistemicTier.Authoritative,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 3,
    progressClaimAllowed: true,
  },
  [EVIDENCE_CLASS_KEYS.System]: {
    classKey: EVIDENCE_CLASS_KEYS.System,
    entityType: 'System',
    tier: AIEvidenceEpistemicTier.Authoritative,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 2,
    progressClaimAllowed: false,
  },
  [EVIDENCE_CLASS_KEYS.Knowledge]: {
    classKey: EVIDENCE_CLASS_KEYS.Knowledge,
    entityType: 'ReadingSession',
    tier: AIEvidenceEpistemicTier.Authoritative,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 3,
    progressClaimAllowed: true,
  },
  [EVIDENCE_CLASS_KEYS.Body]: {
    classKey: EVIDENCE_CLASS_KEYS.Body,
    entityType: 'Workout',
    tier: AIEvidenceEpistemicTier.Authoritative,
    privacyLevel: AIPrivacyLevel.Elevated,
    retrievalPriority: 2,
    progressClaimAllowed: true,
  },
  [EVIDENCE_CLASS_KEYS.Brand]: {
    classKey: EVIDENCE_CLASS_KEYS.Brand,
    entityType: 'Content',
    tier: AIEvidenceEpistemicTier.Authoritative,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 3,
    progressClaimAllowed: true,
  },
  [EVIDENCE_CLASS_KEYS.Career]: {
    classKey: EVIDENCE_CLASS_KEYS.Career,
    entityType: 'CareerDeliverable',
    tier: AIEvidenceEpistemicTier.Authoritative,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 3,
    progressClaimAllowed: true,
  },
  [EVIDENCE_CLASS_KEYS.Spirit]: {
    classKey: EVIDENCE_CLASS_KEYS.Spirit,
    entityType: 'PracticeSessionEvidence',
    tier: AIEvidenceEpistemicTier.Authoritative,
    privacyLevel: AIPrivacyLevel.Elevated,
    retrievalPriority: 3,
    progressClaimAllowed: true,
  },
  [EVIDENCE_CLASS_KEYS.Finance]: {
    classKey: EVIDENCE_CLASS_KEYS.Finance,
    entityType: 'FinanceRecord',
    tier: AIEvidenceEpistemicTier.Authoritative,
    privacyLevel: AIPrivacyLevel.Restricted,
    retrievalPriority: 3,
    progressClaimAllowed: false,
  },
  [EVIDENCE_CLASS_KEYS.Relationships]: {
    classKey: EVIDENCE_CLASS_KEYS.Relationships,
    entityType: 'PresenceSessionEvidence',
    tier: AIEvidenceEpistemicTier.Authoritative,
    privacyLevel: AIPrivacyLevel.Restricted,
    retrievalPriority: 3,
    progressClaimAllowed: true,
  },
  [EVIDENCE_CLASS_KEYS.Mind]: {
    classKey: EVIDENCE_CLASS_KEYS.Mind,
    entityType: 'MindProtocolEvidence',
    tier: AIEvidenceEpistemicTier.Authoritative,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 3,
    progressClaimAllowed: true,
  },
  [EVIDENCE_CLASS_KEYS.Legacy]: {
    classKey: EVIDENCE_CLASS_KEYS.Legacy,
    entityType: 'LegacyRecord',
    tier: AIEvidenceEpistemicTier.Authoritative,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 3,
    progressClaimAllowed: false,
  },
  [EVIDENCE_CLASS_KEYS.DailyAction]: {
    classKey: EVIDENCE_CLASS_KEYS.DailyAction,
    entityType: 'DailyAction',
    tier: AIEvidenceEpistemicTier.Temporary,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 1,
    progressClaimAllowed: false,
  },
  [EVIDENCE_CLASS_KEYS.Proposal]: {
    classKey: EVIDENCE_CLASS_KEYS.Proposal,
    entityType: 'AIProposal',
    tier: AIEvidenceEpistemicTier.Temporary,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 5,
    progressClaimAllowed: false,
  },
  [EVIDENCE_CLASS_KEYS.Insight]: {
    classKey: EVIDENCE_CLASS_KEYS.Insight,
    entityType: 'AIInsight',
    tier: AIEvidenceEpistemicTier.Temporary,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 5,
    progressClaimAllowed: false,
  },
  [EVIDENCE_CLASS_KEYS.ChatTurn]: {
    classKey: EVIDENCE_CLASS_KEYS.ChatTurn,
    entityType: 'ChatTurn',
    tier: AIEvidenceEpistemicTier.Invalid,
    privacyLevel: AIPrivacyLevel.Standard,
    retrievalPriority: 99,
    progressClaimAllowed: false,
  },
};
